version: "3"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "scripts/**/*"

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: false
